name: CI

on:
  push:
    paths-ignore:
      - 'README.md'
    branches-ignore:
      - 'dependabot/**'
  pull_request:

permissions:
  contents: read

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
    - name: Create tests execution report for all test projects
      run: ./test-projects.sh test createTestsExecutionReport
    - name: Check reports were created
      uses: gradle/gradle-build-action@v2
      with:
        arguments: checkReports
  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -i
    - name: Create tests execution report for all test projects
      run: ./test-projects.ps1 test createTestsExecutionReport
    - name: Check reports were created
      uses: gradle/gradle-build-action@v2
      with:
        arguments: checkReports
